version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: seyahat_db
      POSTGRES_USER: seyahat_user
      POSTGRES_PASSWORD: seyahat123
    ports:
      - "5432:5432"

  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/seyahat_db
      SPRING_DATASOURCE_USERNAME: seyahat_user
      SPRING_DATASOURCE_PASSWORD: seyahat123
    depends_on:
      - db
