spring.datasource.url=jdbc:postgresql://localhost:5432/seyahat_db
spring.datasource.username=seyahat_user
spring.datasource.password=seyahat123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.web.cors.allowed-origins=http://localhost:3000
server.port=${PORT:8080}